version: 0.2 
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish AWSLambda1\AWSLambda1\bin\Debug\netcoreapp1.0\publish -c Release -o bin/Release/netcoreapp1.0/publish
      - cd AWSLambda1\AWSLambda1\bin\Debug\netcoreapp1.0\publish
      - zip ../../../../../../Artifacts/AWSLambda1.zip *
      - cd ../../../../../..
  discard-paths: yes
