version: 0.2 
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish MyBirthYearLambdaFunction\myBirthYearLambdaFunction.sln
      - cd AWSLambda1\AWSLambda1\bin\Debug\netcoreapp1.0\publish
      - zip *
